/// Generated by Flutter GetX Starter on 2021-09-25 17:40
import 'package:flutter/material.dart';
import 'package:flutter_localizations/flutter_localizations.dart';
import 'package:get/get_navigation/get_navigation.dart';
import 'package:smart_home_mobile/app/common/base/base_view_view_model.dart';
import 'package:smart_home_mobile/app/common/helper/mqtt_helper.dart';
import 'package:smart_home_mobile/app/presentation/routes/app_pages.dart';
import 'package:smart_home_mobile/app/presentation/translations/translation.dart';
import 'package:smart_home_mobile/env.dart';

void main() {
  MQTTHelper().initialize();
  BuildEnvironment.init(BuildFlavor.dev, "https://", '128.199.168.81:8089');

  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return ScreenUtilInit(
      designSize: Size(375, 812),
      builder: () {
        return GetMaterialApp(
            initialRoute: Routes.LOGIN,
            getPages: AppPages.pages,
            translations: MyTranslations(),
            locale: MyTranslations.locale,
            fallbackLocale: MyTranslations.fallbackLocale,
            theme: ThemeData(
              primarySwatch: Colors.blue,
            ),
            localizationsDelegates: [
              GlobalMaterialLocalizations.delegate,
              GlobalWidgetsLocalizations.delegate,
              GlobalCupertinoLocalizations.delegate,
            ],
            supportedLocales: MyTranslations.locales);
      },
    );
  }
}
